version: "3.8"

services: 
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend

  redis:
    image: redis:latest
    restart: always
    depends_on:
      - db
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  db: 
    image: mysql:5.7
    ulimits:
        nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
          soft: 1048576
          hard: 1048576
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root --password=${DB_PASSWORD_ROOT}"
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
volumes:
  db-data:
  cache:
    driver: local
